# -*- coding: utf-8 -*-
"""project_I_group07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULhlAVdM220wfUcCcW0VuzWrjU2pvrt-

# Project 1: Group 07

## Part I: Replicating Models from Class

### Setup
"""

#Import libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

from scipy.optimize import minimize
from scipy.stats import poisson, nbinom, chi2
from math import factorial, log, exp
from scipy.special import gammaln, factorial

#Mount Drive [to delete]
from google.colab import files
from google.colab import drive
#drive.mount('/content/drive')

#Specify the directory to use
#os.chdir(r'/content/drive/MyDrive/Modeling for Biz Analytics/project-I-group07')

#Specify the directory to use
#os.chdir(os.path.expanduser('~/OneDrive - The University of Texas at Dallas/School/MIS 6386 Modeling for Biz Analytics/Group 7/hw03_group07/'))

data1 = files.upload()

#Read in the dataset
df_billboard = pd.read_csv(r'billboard.csv')

df_billboard.head()

"""### 1. The Poisson Model

#### a) Write code to estimate the parameters of the Poisson model using maximum likelihood estimation (MLE).
"""

# Prepare the data for modeling
exposures = np.array(df_billboard['EXPOSURES'])
people = np.array(df_billboard['PEOPLE'])

"""Poisson PMF (Probability Mass Function) Formula

$$
P(X = k) = \frac{\lambda^k \, e^{-\lambda}}{k!}
$$

Given:
- \( lambda \): The average rate of events per interval.
- \( k\): The exact number of events.

##### 1. The Log-Likelihood (LL)
"""

# lambda param: decision variable (λ)
# exposures (k): number of billboard exposure(s)
# people[i]: the number of people who experienced 'k number' of billboard exposure(s)

def LL_poisson(lambda_param, exposures, people):
    # Unpack lambda parameter
    lambda_param = float(lambda_param[0])

    # Initialize log-likelihood as a scalar
    ll = 0 #Used this approach vs. creating a list because it is computationally more efficient

    # Loop through each exposure level and its observed frequency
    for i in range(len(exposures)):
        k = exposures[i]
        count = people[i]

        '''
        Poisson Probability mass function (PMF) = P(x = k | lambda) = (lambda^k * exp(-lambda)) / k!
        '''
        # Calculate the log of the Poisson PMF (Probability Mass Function) for the current exposure level
        log_pmf = poisson.logpmf(k, lambda_param)

        # Weighted log-likelihood for this exposure level
        ll += count * log_pmf  # Multiply by the number of people (count) at this exposure level

    # Return the total negative log-likelihood
    return -ll # minimize for optmization

"""##### 2. Optimize"""

#Specify the initial guess for lambda
initial_lambda_guess =np.array([1])

# Maximize likelihood

# args = (exposures, people): Input parameters
# bounds = [(0.000001, None)]: Bounds for lambda to ensure it's positive
# tolerance: controls over the stopping criteria for the minimization
# options = 'ftol' (function tolerance): ensures that the function's value changes by less than than 1e-8 before stopping

# Run the optimization
result = minimize(LL_poisson,
                  initial_lambda_guess,
                  args=(exposures, people),
                  method='L-BFGS-B',
                  bounds=[(1e-10, None)],
                  tol = 1e-10,
                  options = {'ftol': 1e-8}
                  )

result

"""#### b) Find estimated parameters and maximum value of the log-likelihood"""

# Extract the estimated lambda and MLE
lambda_mle = result.x[0]

#Convert to positive
max_log_likelihood = -result.fun

print(f"Estimated Lambda (λ): {lambda_mle}")
print(f"Maximum Log-Likelihood: {max_log_likelihood}")

"""#### c) Predict the number of people with 0, ..., 23 exposures based on the Poisson model."""

# Predict the number of people for 0 - 23 exposures
exposures_pred = np.arange(0, 24)
total_people = sum(people)  # Assuming people is already defined in your environment
lambda_mle = lambda_mle  # Assuming lambda_mle is defined as the estimated lambda from MLE

# Calculate the predicted number of people for each exposure level
people_pred_poisson = total_people * (np.exp(-lambda_mle) * lambda_mle**exposures_pred / np.array([factorial(k) for k in exposures_pred]))

# Create a DataFrame to organize the data
df_predictions = pd.DataFrame({
    'Exposure Level': exposures_pred,
    'Predicted People': people_pred_poisson
})

# Display the DataFrame
print("Predictions of people with 0, ...,23 exposures based on the Poisson model")
df_predictions

"""#### d) Explain how the predicted values are obtained using the case of 2 exposures (show your calculations)."""

sum(people)

k = 2
predicted_people_2_exposures = total_people * ((np.exp(-lambda_mle) * lambda_mle**k / factorial(k)))
print(f"Predicted number of people for 2 exposures: {predicted_people_2_exposures}")

"""Poisson PMF (Probability Mass Function) Formula

$$
P(X = k) = \frac{\lambda^k \, e^{-\lambda}}{k!}
$$

Given:
- \( λ = 4.456 \): The average rate of events per interval.
- \( k = 2 \): The exact number of events.

$$
P(X = 2) = 250 * \frac{4.456^2 \cdot e^{-4.456}}{2!} ≈ 28.813
$$

#### e) Graph the original and predicted number of exposures (number of people on the y-axis and the numbers of exposures on the x-axis).
"""

plt.figure(figsize=(10, 6))

# Plot original data as bars
plt.bar(exposures, people, label='Original Data', alpha=0.7, color='blue', width=0.4, align='center')

# define position of bars on x-axis
ind = np.arange(len(exposures))

# define the width of a bar
width = 0.4

# Plot predicted data as bars with a slight offset to avoid overlap
plt.bar(exposures_pred + 0.4, people_pred_poisson, label='Predicted Data (Poisson Model)', alpha=0.7, color='orange', edgecolor = 'black', width=0.4, align='center')

# Labeling the axes and adding a title
plt.xlabel('Number of Exposures')
plt.ylabel('Number of People')
plt.legend()
xticks = plt.xticks(ind + width / 2, df_billboard['EXPOSURES'])
plt.title('Original vs. Predicted Number of People by Exposures Using Poisson Distribution')
plt.show()

"""### 2. The NBD Model

Negative Binomial distribution PMF Formula

$
P(X = k) = \frac{\Gamma(n + k)}{\Gamma(n) \cdot k!} \cdot \left( \frac{\alpha}{\alpha+ 1} \right)^{n} \cdot \left( \frac{1}{\alpha + 1} \right)^k
$

#### a) Write code (for the same dataset) to estimate the parameters of the NBD model using MLE.

Report your code, the estimated parameters and the maximum value of the log-likelihood.

##### 1.  Log-Likelihood
"""

# n, alpha: shape and scale parameters for the gamma distribution
# exposures: size of the number of exposures
# people: the number of people with the corresponding number of billboard exposures

def NLL_nbd(params, exposures, people):
  # unpack parameters
  n, alpha = params # shape and scale parameters for gamma distribution
  (nb_r, nb_p) = (n, alpha / (alpha + 1)) # parameters in the negative binomial distribution

  # calculate log probabilities for all exposures at once
  log_prob = nbinom.logpmf(exposures, nb_r, nb_p, loc = 0)

  # calculate log-likelihood for each exposure count
  ll = people * log_prob

  # sum the negative log-likelihood
  nll = -np.sum(ll)

  return nll

"""##### 2. Optimize"""

# Initial guesses for parameters
params = np.array((1,1)) # initial guess for parameters

nbd_result = minimize(NLL_nbd, # minimize the negative log-likelihood (equivalent to maximizing the log-likelihood)
                args = (exposures, people), # input parameters (not to be altered by the solver)
                x0 = params, # initial guess for lambda
                bounds = [(0.000001, None), (0.000001, None)], # bounds for decision variables
                tol = 1e-10, # convergence tolerance
                options = {'ftol': 1e-8} # fractional tolerance
                )

"""##### 3. Find estimated parameters and maximum value of the log-likelihood"""

# MLE parameters
mle_params_nbd = nbd_result.x
print(f'Estimated n: {mle_params_nbd[0]}\nEstimated α: {mle_params_nbd[1]}')

# maximum value of log-likelihood
mll_nbd = -nbd_result.fun
print(f'Maximum Log-Likelihood: {mll_nbd}')

"""#### b) Predict the number of people with 0, …, 23 exposures based on the NBD model."""

n_mle = mle_params_nbd[0]
alpha_mle = mle_params_nbd[1]

# Prediction for the number of people with different purchase counts
# Calculate expected people count for purchase levels 0 to 23
exposures_pred = np.arange(0, 24)
people_pred = (np.exp(gammaln(exposures_pred + n_mle) - gammaln(n_mle) - gammaln(exposures_pred + 1)) *
               (alpha_mle / (alpha_mle + 1))**n_mle * (1 / (alpha_mle + 1))**exposures_pred)

# Scale predictions to the total number of people observed
total_people = sum(people)
people_pred_scaled = total_people * people_pred

# Create a DataFrame for predictions
df_predictions = pd.DataFrame({
    'Purchase Count': exposures_pred,
    'Predicted People': people_pred_scaled
})

print("\nPredicted number of people for each purchase count level based on NBD:")
print(df_predictions)

"""#### c) Explain how the predicted values are obtained using the case of 2 exposures (show your calculations)."""

# Given parameters: exposure level and observed total number of people
k = 2  # number of exposures we want to predict
total_people = sum(people)  # total observed people, as in the previous code

# Parameters from MLE
n_mle = mle_params_nbd[0]  # Estimated n parameter from MLE
alpha_mle = mle_params_nbd[1]  # Estimated α parameter from MLE

# Calculate predicted number of people with exactly `k` exposures using Negative Binomial formula
predicted_people_2 = total_people * np.exp(
    gammaln(k + n_mle) - gammaln(n_mle) - gammaln(k + 1) +
    n_mle * np.log(alpha_mle / (alpha_mle + 1)) +
    k * np.log(1 / (alpha_mle + 1))
)

print(f"Predicted number of people for 2 exposures (NBD): {predicted_people_2}")

"""Negative Binomial distribution PMF Formula

$
P(X = k) = \frac{\Gamma(n + k)}{\Gamma(n) \cdot k!} \cdot \left( \frac{\alpha}{\alpha+ 1} \right)^{n} \cdot \left( \frac{1}{\alpha + 1} \right)^k
$

Predict values of k = 2 exposures:
-  size parameter **n** (shape of distribution) = 0.96926 \: number of trials until (X=k)
- scale/ dispersion parameter **α** (spread or how much variance deviates from mean)
  - n = 0.96926
  - α = 0.21752


$P(X = 2) = 250 \times \frac{Γ(0.96926)}{Γ(0.96926) \times 2!} \times \big(\frac{0.21752}{0.21752
 + 1}\big)^{0.96926} \times \big(\frac{1}{0.21752 + 1}\big)^{2} ≈ 30.319$

#### d) Graph the original and predicted numbers of exposures.
"""

# Set up bar width for side-by-side placement
bar_width = 0.4

# Plotting the bar chart
plt.figure(figsize=(10, 6))
plt.bar(exposures - bar_width/2, people, bar_width, color='blue', edgecolor='black', label='Original Data')
plt.bar(exposures + bar_width/2, people_pred_scaled, bar_width, color='orange', edgecolor='black', label='Predicted Data (NBD Model)')

# Labeling
plt.xlabel('Number of Exposures')
plt.ylabel('Number of People')
plt.title('Original vs. Predicted Number of People by Exposures Using NBD Distribution')
xticks = plt.xticks(ind + bar_width / 2, df_billboard['EXPOSURES'])
plt.legend()
plt.show()

"""#### e) Evaluate the NBD model vis-à-vis the Poisson model; explain which is better and why."""

# Plotting side-by-side comparison of Poisson and NBD models
bar_width = 0.3

plt.figure(figsize=(14, 8))

# Plot original data
plt.bar(exposures - 0.6, people, bar_width, color='blue', edgecolor='black', label='Original Data')

# Plot Poisson model predictions
plt.bar(exposures_pred, people_pred_poisson, bar_width, color='green', edgecolor='black', label='Predicted Data (Poisson Model)')

# Plot NBD model predictions
plt.bar(exposures + 0.6, people_pred_scaled, bar_width, color='orange', edgecolor='black', label='Predicted Data (NBD Model)')

# Labeling the axes and adding a title
plt.xlabel('Number of Exposures')
plt.ylabel('Number of People')
xticks = plt.xticks(ind + bar_width / 2, df_billboard['EXPOSURES'])
plt.title('Original vs. Predicted Number of People by Exposures Using Poisson and NBD Models')
plt.legend()

plt.show()

"""### 3. The Poisson Regression

In Poisson regression, the expected count \( λ \) for observation \( i \) is modeled as:

$$
\lambda_i = \exp(\beta_0 + \beta_1 x_1^i + \beta_2 x_2^i + \beta_3 x_3^i + \beta_4 x_4^i)
$$

where:
- \( λ \) is the expected count of events for observation \( i \).
- \( β0 \) is the intercept term.
- \( β1, β2, β3, β4 \) are coefficients corresponding to each explanatory variable \( x1, x2, x3, x4 \).
- \( x_j^i \) represents the value of the \( j \)-th variable for observation \( i \).

#### a) Estimate all relevant parameters for Poisson regression using MLE. Report your code, the estimated parameters and the maximum value of the log-likelihood.
"""

#Read in the dataset
data2= files.upload()
kc = pd.read_csv('khakichinos.csv')

kc.head()

"""##### 1. Log Likelihood"""

# Calculated more efficienctly using Vectorized Calculations & Direct Summation

# Prepare input variables
X = kc.drop(['ID', 'NumberofVisits'], axis=1).values  # Drop ID and target column, convert to numpy array
y = kc['NumberofVisits'].values  # Target variable
params = np.ones(X.shape[1] + 1)  # Initial guess for parameters

# Optimized Negative Log-Likelihood function for Poisson regression
def NLL_poisson_reg(params, X, y):
    # Extract lambda_0 and betas
    lambda_0, *betas = params
    betas = np.array(betas)  # Convert to numpy array for vectorized operations

    # Calculate lambdas for each record using vectorized operations
    lambdas = lambda_0 * np.exp(X @ betas)  # Vectorized calculation of lambdas

    # Vectorized negative log-likelihood calculation for all records at once
    nll = -np.sum(poisson.logpmf(y, lambdas))  # Direct summation of log-likelihoods

    return nll

"""##### 2. Optimize"""

# Minimize the negative log-likelihood
soln_poisson_reg = minimize(
    NLL_poisson_reg,           # Minimize the NLL function
    args=(X, y),               # Arguments for the NLL function
    x0=params,                 # Initial guess for parameters
    bounds=[(0.000001, None)] + [(None, None)] * X.shape[1],  # Parameter bounds
    tol=1e-10,                 # Convergence tolerance
    options={'ftol': 1e-8}     # Fractional tolerance
)

"""##### 3. Find estimated parameters and maximum value of the log-likelihood"""

# Extract MLE parameters for Poisson regression
mle_params_poisson_reg = soln_poisson_reg.x

# Print estimated parameters
print(f'Estimated lambda0: {mle_params_poisson_reg[0]}')
for i in range(1, len(mle_params_poisson_reg)):
    print(f'Estimated beta{i}: {mle_params_poisson_reg[i]}')

# Calculate and print maximum value of log-likelihood
mll_poisson_reg = -soln_poisson_reg.fun
print(f'Maximum Log-Likelihood: {mll_poisson_reg}')

# Fit Poisson regression model
X = sm.add_constant(X)  # Add intercept
poisson_model = sm.GLM(y, X, family=sm.families.Poisson()).fit()

print(poisson_model.summary())

"""#### b)  Predict the number of people with 0, ..., 23 visits based on the Poisson regression."""

#Extract estimated coefficients for λ calculation
estimated_params = poisson_model.params

#Calculate λ for each observation
lambda_vals = np.exp(np.dot(X, estimated_params))

#Generate predictions for each exposure level from 0 to 23
exposure_range = np.arange(24)  # Range of exposures to predict (0 to 23)
predicted_counts = []

for k in exposure_range:
    # Calculate the expected number of people with exactly `k` exposures
    # by summing Poisson probabilities for `k` exposures across all observations
    expected_count_k = np.sum(poisson.pmf(k, mu=lambda_vals))
    predicted_counts.append(expected_count_k)

# Create a DataFrame for easier viewing
predicted_counts_poissonreg_df = pd.DataFrame({
    'Number of Visits': exposure_range,
    'Predicted Number of People': predicted_counts
})

# Display the predicted counts DataFrame
predicted_counts_poissonreg_df

"""#### c) Explain how the predicted values are obtained using the case of 2 exposures (show your calculations)."""

#Predict the expected number of people with exactly 2 exposures
k = 2

# Calculate the probability of exactly 2 exposures for each observation
probability_2_exposures = poisson.pmf(k, mu=lambda_vals)

# Sum the probabilities across all observations to get the expected count
predicted_count_2_exposures = np.sum(probability_2_exposures)

# Display the result
print(f"Predicted number of people with exactly {k} exposures: {predicted_count_2_exposures}")

"""Step-by-Step Calculation of P(X = 2) in Poisson Regression

1. **Calculate the Expected Count \( λi \)**

   For each observation \( i \), the expected count \(λi\) is given by:

   $$
   \lambda_i = \lambda_0 \times \exp(\beta_1 x_{1,i} + \beta_2 x_{2,i} + \beta_3 x_{3,i} + \beta_4 x_{4,i})
   $$

   where:
   - λ0 ≈ 0.0437
   - β1 ≈ 0.0941
   - β2 ≈ 0.0044
   - β3 ≈ 0.5887
   - β4 ≈ -0.0359

2. **Compute the Probability of Exactly 2 Exposures**

   We use the Poisson probability mass function (PMF) to compute the probability that each individual has exactly 2 exposures, given by:

   $$
   P(X = 2) = \frac{\lambda_i^2 \exp(-\lambda_i)}{2!}
   $$

3. **Calculate P(X = 2) by Summation**

   $$
   P(X = 2) ≈ 463.329
   $$

#### d) Graph the original and predicted numbers of visits.
"""

# Calculate actual counts from the dataset
actual_counts = kc['NumberofVisits'].value_counts().sort_index()
actual_counts = actual_counts.reindex(exposure_range, fill_value=0)

# Add actual counts to the DataFrame for easy plotting
predicted_counts_poissonreg_df['Actual Number of People'] = actual_counts.values

# Display the predicted counts DataFrame
predicted_counts_poissonreg_df

# Plotting the side-by-side bar chart with specified colors and edge colors
fig, ax = plt.subplots(figsize=(12, 6))
bar_width = 0.4  # Width of the bars

# Plot bars for actual and predicted counts
ax.bar(predicted_counts_poissonreg_df['Number of Visits'] - bar_width/2,
       predicted_counts_poissonreg_df['Actual Number of People'],
       bar_width,
       color='blue',
       edgecolor='black',
       label='Original Data')

ax.bar(predicted_counts_poissonreg_df['Number of Visits'] + bar_width/2,
       predicted_counts_poissonreg_df['Predicted Number of People'],
       bar_width,
       color='orange',
       edgecolor='black',
       label='Predicted Data (Poisson Regression Model)')

# Labeling the chart
ax.set_xlabel('Number of Visits')
ax.set_ylabel('Number of People')
ax.set_title('Actual vs. Predicted Number of People at Each Exposure Level of using Poisson Regression `khakichinos.csv')
ax.legend()

# Show plot
plt.show()

"""### 4. The NBD Regression

#### a) Consider the khakichinos example again. Estimate all relevant parameters for NBD regression using MLE.
Report your code, the estimated parameters and the maximum value of the log-likelihood.

##### 1. Log likelihood
"""

# params: 1) n, alpha 2) betas - coefficients of linear regression
# X: characteristic variables lninc, sex, lnage, hhsize
# y: number of visits for each person

def NLL_nbd_reg(params, X, y):
  # unpack parameters
  n, alpha, *betas = params # n, alpha, and the remaining parameters in betas

  # calculate exp(beta*X) for each record using matrix multiplication
  exp_betaX = np.exp(X @ np.array(betas)) # X @ betas gives the linear combination

  # calculate log-likelihood components
  p1 = gammaln(n + y) - gammaln(n) - gammaln(y + 1) # gamma(k+1) = k! -> gammaln(k+1) = ln(k!)
  p2 = n * (np.log(alpha) - np.log(alpha + exp_betaX))
  p3 = y * (np.log(exp_betaX) - np.log(alpha + exp_betaX))

  # sum the log-likelihood components
  ll = p1 + p2 + p3

  # sum the negative log-likelihood
  nll = -np.sum(ll)

  return nll

"""##### 2. Optimize"""

# Minimize the negative log-likelihood
X = kc.copy()
X = np.array(X.drop(['ID', 'NumberofVisits'], axis = 1))
y = np.array(kc['NumberofVisits'])
params = np.ones(X.shape[1] + 2) # initial guess for parameters

soln_nbd_reg = minimize(NLL_nbd_reg, # minimize the negative log-likelihood (equivalent to maximizing the log-likelihood)
                args = (X, y), # input parameters (not to be altered by the solver)
                x0 = params, # initial guess for parameters
                bounds = [(0.000001, None)] * 2 + [(None, None)] * X.shape[1], # bounds for decision variables
                tol = 1e-10, # convergence tolerance
                options = {'ftol': 1e-8} # fractional tolerance
                )

"""##### 3. Find estimated parameters and maximum value of the log-likelihood"""

# MLE parameters
mle_params_nbd_reg = soln_nbd_reg.x
print(f'Estimated n: {mle_params_nbd_reg[0]}\nEstimated alpha: {mle_params_nbd_reg[1]}\nEstimated beta1: {mle_params_nbd_reg[2]}\nEstimated beta2: {mle_params_nbd_reg[3]}\nEstimated beta3: {mle_params_nbd_reg[4]}\nEstimated beta4: {mle_params_nbd_reg[5]}')

# maximum value of log-likelihood
mll_nbd_reg = -soln_nbd_reg.fun
print(f'Maximum Log-Likelihood: {mll_nbd_reg}')

"""#### b) Predict the number of people with 0, ..., 23 exposures based on the NBD regression."""

def predict_nbd_reg(params, X, y, max_k=23):
    """
    Predict the expected number of people with each visit count from 0 to max_k using the NBD regression model.

    Parameters:
    - params: Estimated parameters from the NBD regression (n, alpha, betas).
    - X: Matrix of characteristic variables.
    - y: Actual number of visits for each person.
    - max_k: The maximum count of visits for prediction (default is 23).

    Returns:
    - A dictionary with visit counts (0 to max_k) as keys and the expected number of people as values.
    """
    # Extract parameters
    n, alpha, *betas = params
    betas = np.array(betas)  # Convert betas to a numpy array

    # Calculate exp(beta * X) for each record using matrix multiplication
    exp_betaX = np.exp(X @ betas)

    # Limit unique counts to the range [0, max_k]
    unique_counts = np.arange(0, max_k + 1)

    # Dictionary to store predictions for each k
    pred = {}

    # Calculate the probability p(x = k) for each record and sum up
    for k in unique_counts:
        # Summing the NBD probabilities across all individuals for the specific count k
        pred[k] = np.sum([nbinom.pmf(k, n, alpha / (alpha + exp_betaX_i), loc=0) for exp_betaX_i in exp_betaX])

    # Sort dictionary by visit count (although in range order, sorting ensures consistent output)
    pred = dict(sorted(pred.items()))

    return pred

# Example usage after defining `mle_params_nbd_reg`, `X`, and `y`:
pred_nbd_reg = predict_nbd_reg(mle_params_nbd_reg, X, y)
pred_nbd_reg

# create a dataframe to store actual counts
actual_df = kc.groupby('NumberofVisits')['ID'].count().reset_index()
actual_df.columns = ['NumberofVisits', 'ActualVisitorCount']

# create a dataframe to store predicted counts
pred_df = pd.DataFrame({'NumberofVisits': list(pred_nbd_reg.keys()),
                        'PredictedVisitorCount': list(pred_nbd_reg.values())})

# merge actual and predicted counts on NumberofVisits
kc_nbd_reg = pd.merge(actual_df, pred_df, on = 'NumberofVisits', how = 'outer').fillna(0)

# combine groups with number of visits
kc_nbd_reg_combined = kc_nbd_reg.copy()
kc_nbd_reg_combined.loc[kc_nbd_reg_combined['NumberofVisits'] >= 23, 'NumberofVisits'] = 23
kc_nbd_reg_combined = kc_nbd_reg_combined.groupby('NumberofVisits').sum().reset_index()
kc_nbd_reg_combined

""" #### d) Explain how the predicted values are obtained using the case of 2 exposures (show your calculations)."""

# unpack estimated parameters
mle_n_nbd_reg, mle_alpha_nbd_reg, *mle_betas_nbd_reg = mle_params_nbd_reg

# calculate estimated exp_betaX
mle_exp_betaX_nbd_reg = np.exp(X @ np.array(mle_betas_nbd_reg))

# predicted values for the case of 2 visits
k = 2

# sum up the probabilities of 2 visits for each exp(betaX)_i
pred_2_visits_nbd_reg = np.sum(nbinom.pmf(k, mle_n_nbd_reg, mle_alpha_nbd_reg / (mle_alpha_nbd_reg + mle_exp_betaX_nbd_reg)))
print(f'The predicted number of people for the case of 2 visits: {pred_2_visits_nbd_reg}.')

"""Step-by-Step Calculation of P(X = 2) in NBD Regression

1. **Calculate the Expected Count \(λi\)**

   For each observation \(i\), the expected count \(λi\) is given by:

   $$
   \mu_i = \exp(\beta_1 x_{1,i} + \beta_2 x_{2,i} + \beta_3 x_{3,i} + \beta_4 x_{4,i})
   $$

   where:
   - β1 = 0.0733
   - β2 = -0.0089
   - β3 = 0.9027
   - β4 = -0.0243

2. **Compute the Probability of Exactly 2 Exposures**

   For each observation, we use the Negative Binomial probability mass function (PMF) to compute the probability that each individual has exactly 2 exposures, given by:

   $$
   P(X = 2) = \frac{\Gamma(n + 2)}{\Gamma(n) \times 2!} \times \big(\frac{\alpha}{\alpha + \mu_i}\big)^{n} \times \big(\frac{\mu_i}{\alpha + \mu_i}\big)^{2}
   $$
   
   where:
   - n = 0.1387
   - α = 8.2100

3. **Calculate P(X = 2) by Summation**

   We then sum up all the probabilities of exactly 2 exposures across all observations.
   $$
   P(X = 2) ≈ 120.131
   $$

#### d) Graph the original and predicted numbers of exposures.
"""

# Plotting the side-by-side bar chart with specified colors and edge colors
fig, ax = plt.subplots(figsize=(12, 6))
bar_width = 0.4  # Width of the bars

# Plot bars for actual and predicted counts
ax.bar(kc_nbd_reg_combined['NumberofVisits'] - bar_width/2,
       kc_nbd_reg_combined['ActualVisitorCount'],
       bar_width,
       color='blue',
       edgecolor='black',
       label='Original Data')

ax.bar(kc_nbd_reg_combined['NumberofVisits'] + bar_width/2,
       kc_nbd_reg_combined['PredictedVisitorCount'],
       bar_width,
       color='orange',
       edgecolor='black',
       label='Predicted Data (NBD Regression Model)')

# Labeling the chart
ax.set_xlabel('Number of Visits')
ax.set_ylabel('Number of People')
ax.set_title("Actual vs. Predicted Number of People at Each Visit Count of using NBD Regression `khakichinos.csv'")
ax.legend()

# Show plot
plt.show()

"""#### e) Evaluate the NBD regression vis-à-vis the Poisson regression; explain which is better and why."""

# Define bar width for side-by-side comparison
bar_width = 0.25

plt.figure(figsize=(14, 8))

# Plot actual data (Original Data)
plt.bar(kc_nbd_reg_combined['NumberofVisits'] - bar_width,
        kc_nbd_reg_combined['ActualVisitorCount'],
        bar_width,
        color='blue',
        edgecolor='black',
        label='Original Data')

# Plot Poisson regression model predictions
plt.bar(predicted_counts_poissonreg_df['Number of Visits'],
        predicted_counts_poissonreg_df['Predicted Number of People'],
        bar_width,
        color='green',
        edgecolor='black',
        label='Predicted Data (Poisson Model Regression)')

# Plot NBD regression model predictions
plt.bar(kc_nbd_reg_combined['NumberofVisits'] + bar_width,
        kc_nbd_reg_combined['PredictedVisitorCount'],
        bar_width,
        color='orange',
        edgecolor='black',
        label='Predicted Data (NBD Model Regression)')

# Labeling the axes and adding a title
plt.xlabel('Number of Visits')
plt.ylabel('Number of People')
plt.title('Actual vs. Predicted Number of People by Visit Count Using Poisson Regression and NBD Regression Models')
plt.legend()

# Display plot
plt.show()

"""## Part II: Analysis of New Data

### 1. Read `books01.csv`, with the structure of the dataset used in the *billboard exposures* example
"""

#Read in the dataset
data3 = files.upload()
df_books = pd.read_csv(r'books.csv')

df_books.head()

"""#### a) Generate books01.csv
With the structure of the dataset used in the billboard exposures example (i.e., with only two columns – (i) the number purchases, and (ii) the number of people making the corresponding number of purchases)
"""

#WITH ONLY B&N.com

# Step 1: Get a DataFrame with all unique user IDs
all_users = df_books[['userid']].drop_duplicates()

# Step 2: Filter for only rows where the domain is 'barnesandnoble.com' and aggregate total purchases by user
df_books_bn = df_books[df_books['domain'] == 'barnesandnoble.com']
user_purchases = df_books_bn.groupby('userid')['qty'].sum().reset_index()
user_purchases.columns = ['userid', 'total_purchases']  # Rename for clarity

# Step 3: Merge with all users to include those with 0 purchases
# Fill missing values in 'total_purchases' with 0 for users with no purchases
user_purchases = all_users.merge(user_purchases, on='userid', how='left').fillna({'total_purchases': 0})

# Step 4: Count the number of people (users) for each unique purchase count, including 0 purchases
books_summary = user_purchases['total_purchases'].value_counts().reset_index()
books_summary.columns = ['number_of_purchases', 'number_of_people']

# Step 5: Sort the DataFrame by number of purchases
books_summary = books_summary.sort_values(by='number_of_purchases').reset_index(drop=True)

# Print the result to verify
print(books_summary.head())

#Save to CSV
books_summary.to_csv("books01.csv", index=False)
print("books01.csv created!")

# read in `books01.csv`
df_books01 = pd.read_csv(r'books01.csv')

# print the first and last 10 records
print(f'First 10 records of `books01.csv`:\n{df_books01.head(10)}')
print(f'Last 10 records of `books01.csv`:\n{df_books01.tail(10)}')

"""#### b. Generate books02.csv

With the structure of the dataset used in the khakichinos example, with a new column containing a count of the number of books purchased from barnesandnoble.com by each customer, while keeping the demographic variables (remember to drop date, product, and price).
"""

## with only b&n count not total_purchases
# Step 1: Filter for purchases made on barnesandnoble.com
barnesandnoble_books = df_books[df_books['domain'] == 'barnesandnoble.com']

# Step 2: Calculate purchases from barnesandnoble.com only
barnesandnoble_counts = barnesandnoble_books.groupby('userid')['qty'].sum().reset_index()
barnesandnoble_counts.columns = ['userid', 'barnesandnoble_purchases']  # Rename for clarity

# Step 3: Get the demographic data and ensure unique users
df_demographics = df_books[['userid', 'education', 'region', 'hhsz', 'age', 'income', 'child', 'race', 'country']].drop_duplicates()

# Step 4: Merge demographic data with Barnes & Noble purchases
# This will add the `barnesandnoble_purchases` column to the DataFrame
df_books02 = pd.merge(df_demographics, barnesandnoble_counts, on='userid', how='left')

# Step 5: Fill NaN values in 'barnesandnoble_purchases' with 0
# for customers with no purchases from barnesandnoble.com
df_books02['barnesandnoble_purchases'] = df_books02['barnesandnoble_purchases'].fillna(0)

# Step 6: Save to CSV as books02.csv
df_books02.to_csv('books02.csv', index=False)

print("books02.csv created!")

# Read in `books02.csv`
df_books02 = pd.read_csv(r'books02.csv')

# print the first and last 10 records
print(f'First 10 records of `books02.csv`')
df_books02.head(10)

#Print the last 10 records
df_books02.tail()

"""### 2. Develop a Poisson model using books01.csv.

#### a) Report your code, the estimated parameters and the maximum value of the log-likelihood (and any other information you believe is relevant).
"""

# Prepare the data for modeling
purchases = np.array(df_books01['number_of_purchases'])
people = np.array(df_books01['number_of_people'])

"""### 1. Log Likelihood"""

# lambda param: decision variable (λ)
# qty_purchases (k): number of billboard exposure(s)
# qty_people[i]: the number of people who bought 'k number' of purchases(s)

def LL_poisson2(lambda_param, purchases, people):
    # Unpack lambda parameter
    lambda_param = float(lambda_param[0])

    # Initialize log-likelihood as a scalar
    ll = 0 #Used this approach vs. creating a list because it is computationally more efficient

    # Loop through each exposure level and its observed frequency
    for i in range(len(purchases)):
        k = purchases[i]
        count = people[i]

        # Calculate the log of the Poisson PMF for the current exposure level

        '''
        Poisson Probability mass function (PMF) = P(x = k | lambda) = (lambda^k * exp(-lambda)) / k!
        '''
        # Calculate the log of the Poisson PMF (Probability Mass Function) for the current exposure level
        log_pmf = poisson.logpmf(k, lambda_param)

        # Weighted log-likelihood for this exposure level
        ll += count * log_pmf  # Multiply by the number of people (count) at this exposure level

    # Return the negative log-likelihood for optimization
    return -ll

"""##### 2. Optimize"""

#Specify the initial guess for lambda
initial_lambda_guess =np.array([1])

# Maximize likelihood

# args = (exposures, people): Input parameters
# bounds = [(0.000001, None)]: Bounds for lambda to ensure it's positive
# tolerance: controls over the stopping criteria for the minimization
# options = 'ftol' (function tolerance): ensures that the function's value changes by less than than 1e-8 before stopping

# Run the optimization
result2 = minimize(LL_poisson2,
                  initial_lambda_guess,
                  args=(purchases, people),
                  method='L-BFGS-B',
                  bounds=[(1e-10, None)],
                  tol = 1e-10,
                  options = {'ftol': 1e-8}
                  )

result2

"""##### 3. Find estimated parameters and maximum value of the log-likelihood"""

# Extract the estimated lambda (mean rate of purchases)
lambda_mle1 = result2.x[0]

# Maximum Log-Likelihood
max_log_likelihood = -result2.fun  # Convert NLL back to LL by negating


print(f"MLE Estimate of λ (lambda): {lambda_mle1}")
print(f"Maximum Log-Likelihood: {max_log_likelihood}")

"""### 3. Develop a Poisson model using `books02.csv`, i.e., by ignoring the independent variables available.

#### a) Report your code and confirm that the estimated parameters and the maximum value of the log-likelihood are identical to those obtained with the Poisson model developed using books01.csv.

##### 1. Log Likelihood
"""

#Prepare the target variable (people)
people = df_books02['barnesandnoble_purchases'].values

# Define the Log-Likelihood function for the Poisson model
def LL_poisson(lambda_param, people):
    lambda_param = float(lambda_param[0])  # Unpack lambda parameter
    ll = 0  # Initialize log-likelihood as a scalar

    # Calculate log-likelihood for each count in 'people'
    for count in people:
        log_pmf = poisson.logpmf(count, lambda_param)  # Log of Poisson PMF
        ll += log_pmf  # Accumulate log-likelihood

    return -ll  # Negative for optimization

"""##### 2. Optimize"""

# Initial guess for lambda
initial_lambda_guess = np.array([1])

# Run the optimization to find the MLE for lambda
result3 = minimize(LL_poisson,
                  initial_lambda_guess,
                  args=(people,),
                  method='L-BFGS-B',
                  bounds=[(1e-10, None)],  # Lambda must be positive
                  tol=1e-10,
                  options={'ftol': 1e-8})

"""#####3. Find estimated parameters and maximum value of the log-likelihood"""

# Extract the estimated lambda (mean rate of purchases)
lambda_mle = result3.x[0]

# Maximum Log-Likelihood
max_log_likelihood = -result3.fun  # Convert NLL back to LL by negating

print(f"MLE Estimate of λ (lambda): {lambda_mle}")
print(f"Maximum Log-Likelihood: {max_log_likelihood}")

"""#### b) Predict the number of people with 0, ..., 20, 20+ purchases based on the Poisson model."""

purchases_modified = np.where(df_books02['barnesandnoble_purchases'] > 20, 21, df_books02['barnesandnoble_purchases'])

# Then, use purchases_modified in the subsequent analysis steps
people = purchases_modified
unique_counts = np.unique(people)
total_people = len(people)

# Calculate the predicted counts based on the Poisson model with lambda_mle
predicted_counts = [total_people * poisson.pmf(count, lambda_mle) for count in unique_counts]

# Calculate actual counts from data (with purchases > 20 grouped into 21)
actual_counts = [np.sum(people == count) for count in unique_counts]

# Create a DataFrame to compare actual and predicted counts
df_comparison = pd.DataFrame({
    'Purchase Count': unique_counts,
    'Actual Number of People': actual_counts,
    'Predicted Number of People': predicted_counts
})

# Display the DataFrame to compare actual vs. predicted counts
df_comparison

"""#### c) Explain how the predicted values are obtained using the case of 2 purchases (show your calculations)."""

#Calculate the predicted number of people with exactly 2 purchases
k = 2  # Desired number of purchases to predict
total_people = len(people)  # Total number of entries

# Calculate the probability of exactly 2 purchases using the Poisson PMF
prob_k_equals_2 = poisson.pmf(k, lambda_mle)

# Scale by the total number of people to get the predicted count
predicted_people_2 = prob_k_equals_2 * total_people

print(f"Predicted number of people with exactly 2 purchases: {predicted_people_2}")

total_people

"""Poisson PMF (Probability Mass Function) Formula

$$
P(X = k) = \frac{\lambda^k \, e^{-\lambda}}{k!}
$$

Given:
- \( λ = 0.7485 \): The average rate of events per interval.
- \( k = 2 \): The exact number of events.

$$
P(X = 2) = 9451 * \frac{0.7485^2 \cdot e^{-0.7485}}{2!} ≈ 1252.447
$$

#### d) Graph the original and predicted number of purchases.
"""

# Plotting the side-by-side bar chart for actual vs predicted counts using df_comparison
fig, ax = plt.subplots(figsize=(12, 6))
bar_width = 0.4  # Width of the bars

# Plot bars for actual and predicted counts
ax.bar(df_comparison['Purchase Count'] - bar_width/2,
       df_comparison['Actual Number of People'],
       bar_width,
       color='blue',
       edgecolor='black',
       label='Actual Number of People')

ax.bar(df_comparison['Purchase Count'] + bar_width/2,
       df_comparison['Predicted Number of People'],
       bar_width,
       color='orange',
       edgecolor='black',
       label='Predicted Number of People (Poisson Model)')

# Labeling the chart
ax.set_xlabel('Purchase Count')
ax.set_ylabel('Number of People')
ax.set_title("Actual vs. Predicted Number of People by Purchase Count using Poisson Model for `books02.csv`")
ax.legend()

# Customizing x-ticks to include "20+"
ax.set_xticks(df_comparison['Purchase Count'])
ax.set_xticklabels([str(int(x)) if x < 21 else "20+" for x in df_comparison['Purchase Count']])

# Show plot
plt.show()

"""### 4. Develop an NBD model using `books01.csv`.

##### 1. Log Likelihood
"""

# Prepare the data for modeling
purchases = np.array(df_books01['number_of_purchases'])
people = np.array(df_books01['number_of_people'])

# Define the Negative Log-Likelihood function for the NBD model
def NLL_nbd(params, purchases, people):
    # unpack parameters
    n, alpha = params # shape and scale parameters for gamma distribution
    (nb_r, nb_p) = (n, alpha / (alpha + 1)) # parameters in the negative binomial distribution

    # calculate log probabilities for all purchases at once
    log_prob = nbinom.logpmf(purchases, nb_r, nb_p, loc = 0)

    # calculate log-likelihood for each purchase count
    ll = people * log_prob

    # sum the negative log-likelihood
    nll = -np.sum(ll)

    return nll # return the negative log-likelihood

"""##### 2. Optimize"""

# Initial guesses for parameters
params = np.array((1, 1))  # Initial guess for n and alpha

# Perform MLE for n and alpha
nbd_result = minimize(NLL_nbd,  # Minimize the negative log-likelihood
                      args=(purchases, people),  # Input data
                      x0=params,  # Initial guess for n and alpha
                      bounds=[(0.000001, None), (0.000001, None)],  # Parameter bounds to keep positive
                      tol=1e-10,  # Convergence tolerance
                      options={'ftol': 1e-8})  # Fractional tolerance

"""##### 3. Find estimated parameters and maximum value of the log-likelihood"""

# MLE parameters
mle_params_nbd = nbd_result.x
print(f'Estimated n: {mle_params_nbd[0]}\nEstimated α: {mle_params_nbd[1]}')

# Maximum value of log-likelihood
mll_nbd = -nbd_result.fun
print(f'Maximum Log-Likelihood: {mll_nbd}')

"""### 5. Develop an NBD model using `books02.csv`.

##### 1. Log Likelihood
"""

# Extract the required columns
purchases = df_books02['barnesandnoble_purchases'].values  # Number of purchases per user
people = np.ones(len(purchases))  # Number of people per record, assumed 1 per user

# Define the Negative Log-Likelihood function for the NBD model with vectorization
def NLL_nbd(params, purchases, people):
    n, alpha = params
    nb_r = n
    nb_p = alpha / (alpha + 1)

    # Vectorized log-likelihood calculation
    log_likelihood = people * nbinom.logpmf(purchases, nb_r, nb_p, loc=0)
    nll = -np.sum(log_likelihood)  # Total negative log-likelihood

    return nll

"""##### 2. Optimize"""

# Initial guesses for parameters
params = np.array((1, 1))  # Initial guess for n and alpha

# Perform MLE for n and alpha
nbd_result = minimize(NLL_nbd,  # Minimize the negative log-likelihood
                      args=(purchases, people),  # Input data
                      x0=params,  # Initial guess for n and alpha
                      bounds=[(0.000001, None), (0.000001, None)],  # Parameter bounds to keep positive
                      tol=1e-6,  # Relaxed tolerance
                      options={'ftol': 1e-6})  # Relaxed fractional tolerance

# MLE parameters
mle_params_nbd = nbd_result.x
print(f'Estimated n: {mle_params_nbd[0]}\nEstimated α: {mle_params_nbd[1]}')

# Maximum value of log-likelihood
mll_nbd = -nbd_result.fun
print(f'Maximum Log-Likelihood: {mll_nbd}')

"""##### 3. Find estimated parameters and maximum value of the log-likelihood

### b) Predict the number of people with 0, ..., 20, 20+ purchases based on the NBD model.
"""

n_est = mle_params_nbd[0]
alpha_mle = mle_params_nbd[1]

# Calculate probability of success parameter p for the Negative Binomial
nb_p = alpha_mle / (alpha_mle + 1)

# Modify purchases to cap values above 20 to 21
purchases_modified = np.where(df_books02['barnesandnoble_purchases'] > 20, 21, df_books02['barnesandnoble_purchases'])

# Prepare data for analysis
people = purchases_modified
unique_counts = np.unique(people)
total_people = len(people)

# Calculate predicted counts using the Negative Binomial model with estimated parameters
predicted_counts = [total_people * nbinom.pmf(count, n_est, nb_p) for count in unique_counts]

# Calculate actual counts from data (with purchases > 20 grouped into 21)
actual_counts = [np.sum(people == count) for count in unique_counts]

# Create a DataFrame to compare actual and predicted counts
df_comparison2 = pd.DataFrame({
    'Purchase Count': unique_counts,
    'Actual Number of People': actual_counts,
    'Predicted Number of People': predicted_counts
})

df_comparison2

"""#### c)  Explain how the predicted values are obtained using the case of 2 purchases (show your calculations)."""

# Retrieve predicted number of people with exactly 2 purchases
predicted_people_2_purchases = df_comparison2.loc[df_comparison['Purchase Count'] == 2, 'Predicted Number of People'].values[0]

print(f"Predicted number of people with exactly 2 purchases: {predicted_people_2_purchases}")

"""Negative Binomial distribution PMF Formula

$
P(X = k) = \frac{\Gamma(n + k)}{\Gamma(n) \cdot k!} \cdot \left( \frac{\alpha}{\alpha+ 1} \right)^{n} \cdot \left( \frac{1}{\alpha + 1} \right)^k
$

Predict values of k = 2 exposures:
-  size parameter **n** (shape of distribution) = 0.96926 \: number of trials until (X=k)
- scale/ dispersion parameter **α** (spread or how much variance deviates from mean)
  - n = 0.0813
  - α = 0.2192


$P(X = 2) = 9451 \times \frac{Γ(0.0813 + 2)}{Γ(0.0813) \times 2!} \times \big(\frac{0.2192}{0.2192
 + 1}\big)^{0.08134} \times \big(\frac{1}{0.2192 + 1}\big)^{2} \approx 243.188$

#### d) Graph the original and predicted number of purchases.
"""

# Plotting the side-by-side bar chart for actual vs predicted counts using df_comparison
fig, ax = plt.subplots(figsize=(12, 6))
bar_width = 0.4  # Width of the bars

# Plot bars for actual and predicted counts
ax.bar(df_comparison2['Purchase Count'] - bar_width/2,
       df_comparison2['Actual Number of People'],
       bar_width,
       color='blue',
       edgecolor='black',
       label='Actual Number of People')

ax.bar(df_comparison2['Purchase Count'] + bar_width/2,
       df_comparison2['Predicted Number of People'],
       bar_width,
       color='orange',
       edgecolor='black',
       label='Predicted Number of People (NBD Model)')

# Labeling the chart
ax.set_xlabel('Purchase Count')
ax.set_ylabel('Number of People')
ax.set_title("Actual vs. Predicted Number of People by Purchase Count using NBD Model for `books02.csv`")
ax.legend()

# Customizing x-ticks to include "20+"
ax.set_xticks(df_comparison2['Purchase Count'])
ax.set_xticklabels([str(int(x)) if x < 21 else "20+" for x in df_comparison2['Purchase Count']])

# Show plot
plt.show()

"""### 6. Calculate the values of (i) reach, (ii) average frequency, and (iii) gross ratings points (GRPs) based on the NBD model"""

# Convert 'Purchase Count' to integer for consistency
df_comparison2['Purchase Count'] = df_comparison2['Purchase Count'].astype(int)

# Calculate reach as the proportion of the population making at least 1 purchase
reach_percentage = df_comparison2[df_comparison2['Purchase Count'] > 0]['Actual Number of People'].sum() / df_comparison2['Actual Number of People'].sum() * 100
print(f"Reach (proportion of population making at least 1 purchase) is {reach_percentage:.2f}%.")

# Calculate average frequency by dividing expected purchases by the reach proportion
expected_purchases = n_est/alpha_mle
average_frequency = expected_purchases / (reach_percentage / 100)
print(f"Average frequency (average number of purchases among those who purchased) is {average_frequency:.4f}.")

# Calculate GRPs by multiplying reach (in %) by average frequency
GRPs = reach_percentage * average_frequency
print(f"Gross rating points (average number of purchases per 100 people) is {GRPs:.4f}.")

"""### 7. Identify all independent variables with missing values.

#### a) How many values are missing in each?
Drop any variable
with many missing values (specify how you are defining “many”). If the number of missing values is small (again,
specify how you are defining “small”), delete the rows involved. For the remaining variables (if any), replace the
missing values with the means of the corresponding variables. Explain the steps taken; report your code.
"""

# Check for missing values in each column of df_books02
missing_values = df_books02.isnull().sum()

print(f'Number of Missing Values in Each Column\n{missing_values}')

# get the total number of records
total_records = df_books02.shape[0]

# calculate the proportion of missing values in each category and format as a percentage
missing_values_percentage = ((df_books02.isnull().sum() / total_records)).apply(lambda x: f'{x:.2%}')

# display the result in a formatted way
print(f'Percentage of Missing Values\n{missing_values_percentage}')

"""

    - Drop education because 73.16% of the values are missing.
    - Remove rows with missing values in region and age columns.

"""

# drop education variable
df_books03 = df_books02.copy()
df_books03 = df_books03.drop('education', axis=1)

# drop rows with missing values in region and age columns
df_books03 = df_books03.dropna(subset=['region', 'age'])

df_books03.head()

# Re check for missing values in each column of df_books02
missing_values = df_books03.isnull().sum()

print(f'Number of Missing Values in Each Column\n{missing_values}')

"""### 8. Incorporate all the available customer characteristics and estimate all relevant parameters for Poisson regression using MLE.

#### a) Report your code, the estimated parameters and the maximum value of the log-likelihood (and any other information you believe is relevant).

##### 1. Log-likelihood
"""

# Optimized NLL function for Poisson regression
def NLL_poisson_reg_books2(params, X, y):
    lambda_0, *betas = params  # parameters for regression - lambda_0 and the remaining parameters in betas

    # Calculate lambda for each record using matrix multiplication and vectorized operations
    lambdas = lambda_0 * np.exp(X @ np.array(betas))

    # Calculate the log-likelihood for all records at once
    ll = poisson.logpmf(y, lambdas)

    # Sum negative log-likelihood over all records
    nll = -np.sum(ll)

    return nll  # return the negative log-likelihood

"""##### 2. Optimize"""

# Convert input data to numpy arrays
X = df_books03.copy()
X = np.array(X.drop(['userid', 'barnesandnoble_purchases'], axis=1))
y = np.array(df_books03['barnesandnoble_purchases'])

# Initial guess for parameters
params = np.ones(X.shape[1] + 1)

# Optimization using the minimize function
soln_poisson_reg_books2 = minimize(
    NLL_poisson_reg_books2,  # minimize the negative log-likelihood (equivalent to maximizing the log-likelihood)
    args=(X, y),  # input parameters (not to be altered by the solver)
    x0=params,  # initial guess for parameters
    bounds=[(0.000001, None)] + [(None, None)] * X.shape[1],  # bounds for decision variables
    tol=1e-10,  # convergence tolerance
    options={'ftol': 1e-8}  # fractional tolerance
)

"""##### 3. Find estimated parameters and maximum value of the log-likelihood"""

# MLE parameters
mle_lambda0_poisson_reg_books2, *mle_betas_poisson_reg_books2 = soln_poisson_reg_books2.x
print(f'Estimated lambda0: {mle_lambda0_poisson_reg_books2}')
for x, beta in enumerate(mle_betas_poisson_reg_books2):
    print(f'Estimated beta{x+1}: {beta}')

# Maximum value of log-likelihood
mll_poisson_reg_books2 = -soln_poisson_reg_books2.fun
print(f'Maximum Log-Likelihood: {mll_poisson_reg_books2}')

"""#### b)  What are the managerial takeaways – which customer characteristics seem to be important?

Please see report

####c) Predict the number of people with 0, ..., 20, 20+ purchases based on the Poisson regression.
"""

def predict_poisson_reg_books2(params, X, y):
  # unpack parameters
  lambda_0, *betas = params # lambda_0 and the remaining parameters in betas

  # assume each group has m independent individuals with lambda_i, the expected number of people with k purchases is m * p(x = k | lambda_i)
  # assume each record is a separate group, then the expected number of people with k purchases is p(x = k | lambda_i)
  # calculate p(x = k) for each lambda_i and sum up to get the expected number of people with k purchases

  # calculate lambda for each record using matrix multiplication
  lambdas = lambda_0 * np.exp(X @ np.array(betas))

  # get unique values of y to calculate probabilities for each unique count
  unique_counts = np.unique(y)

  # create a PMF matrix for each unique count k across all samples
  pmf_matrix = np.array([
      poisson.pmf(unique_counts, lambda_i) for lambda_i in lambdas])

  # sum probabilities across all samples for each k value
  pred = np.sum(pmf_matrix, axis = 0) # sum along the samples (axis = 0) for each unique k

  # sort dictionary by visit count
  pred_dict = dict(zip(unique_counts, pred))
  pred_dict = dict(sorted(pred_dict.items()))

  return pred_dict

# make predictions
pred_poisson_reg_books2 = predict_poisson_reg_books2(soln_poisson_reg_books2.x, X, y) # make predictions

# create a dataframe to store actual counts
actual_df = df_books03.groupby('barnesandnoble_purchases')['userid'].count().reset_index()
actual_df.columns = ['NumberofPurchases', 'ActualCustomerCount']

# create a dataframe to store predicted counts
pred_df = pd.DataFrame({'NumberofPurchases': list(pred_poisson_reg_books2.keys()),
                        'PredictedCustomerCount': list(pred_poisson_reg_books2.values())})

# merge actual and predicted counts on NumberofPurchases
books2_poisson_reg = pd.merge(actual_df, pred_df, on = 'NumberofPurchases', how = 'outer').fillna(0)

# combine groups with number of purchases > 20
books2_poisson_reg_combined = books2_poisson_reg.copy()
books2_poisson_reg_combined.loc[books2_poisson_reg_combined['NumberofPurchases'] > 20, 'NumberofPurchases'] = 21
books2_poisson_reg_combined = books2_poisson_reg_combined.groupby('NumberofPurchases').sum().reset_index()

# convert number of purchases into integer
books2_poisson_reg_combined['NumberofPurchases'] = books2_poisson_reg_combined['NumberofPurchases'].astype(int)
books2_poisson_reg_combined

"""#### d) Explain how the predicted values are obtained using the case of 2 purchases (show your calculations)."""

# calculate estimated lambda_i's
mle_lambdas_poisson_reg_books2 = mle_lambda0_poisson_reg_books2 * np.exp(X @ np.array(mle_betas_poisson_reg_books2))

# predicted values for the case of 2 purchases
k = 2

# sum up the probabilities of 2 purchases for each lambda_i
pred_2_purchases_poisson_reg_books2 = np.sum(poisson.pmf(k, mle_lambdas_poisson_reg_books2, loc = 0))
print(f'The predicted number of people for the case of 2 purchases: {pred_2_purchases_poisson_reg_books2}.')

"""Step-by-Step Calculation of P(X = 2) in Poisson Regression

1. **Calculate the Expected Count \( λi \)**

   For each observation \( i \), the expected count \(λi\) is given by:

   $$
   \lambda_i = \exp(\beta_0 + \beta_1 x_{1,i} + \beta_2 x_{2,i} + \beta_3 x_{3,i} + \beta_4 x_{4,i} + \beta_5 x_{5,i} + \beta_6 x_{6,i} + \beta_7 x_{7,i})
   $$

   where:
   - λ0 ≈ 0.9502
   - β1 ≈ -0.1023
   - β2 ≈ -0.0154
   - β3 ≈ 0.0250
   - β4 ≈ 0.0150
   - β5 ≈ -0.0744
   - β6 ≈ -0.2072
   - β7 ≈ -0.1196

2. **Compute the Probability of Exactly 2 Exposures**

   We use the Poisson probability mass function (PMF) to compute the probability that each individual has exactly 2 exposures, given by:

   $$
   P(X = 2) = \frac{\lambda_i^2 \exp(-\lambda_i)}{2!}
   $$

3. **Calculate P(X = 2) Using the Poisson PMF**

   $$
   P(X = 2) ≈ 1245.068
   $$

#### d) Graph the original and predicted number of purchases.
"""

# Plotting the side-by-side bar chart for actual vs predicted counts using df_comparison
fig, ax = plt.subplots(figsize=(12, 6))
bar_width = 0.4  # Width of the bars

# Plot bars for actual and predicted counts
ax.bar(books2_poisson_reg_combined['NumberofPurchases'] - bar_width/2,
       books2_poisson_reg_combined['ActualCustomerCount'],
       bar_width,
       color='blue',
       edgecolor='black',
       label='Actual Number of People')

ax.bar(books2_poisson_reg_combined['NumberofPurchases'] + bar_width/2,
       books2_poisson_reg_combined['PredictedCustomerCount'],
       bar_width,
       color='orange',
       edgecolor='black',
       label='Predicted Number of People (Poisson Regression Model)')

# Labeling the chart
ax.set_xlabel('Purchase Count')
ax.set_ylabel('Number of People')
ax.set_title("Actual vs. Predicted Number of People by Purchase Count using Poisson Regression Model for `books02.csv`")
ax.legend()

# Customizing x-ticks to include "20+"
ax.set_xticks(books2_poisson_reg_combined['NumberofPurchases'])
ax.set_xticklabels([str(int(x)) if x < 21 else "20+" for x in books2_poisson_reg_combined['NumberofPurchases']])

# Show plot
plt.show()

"""### 9. Estimate all relevant parameters for NBD regression using MLE.

#### a) Report your code, the estimated parameters and
the maximum value of the log-likelihood (and any other information you believe is relevant). What are the
managerial takeaways – which customer characteristics seem to be important?

##### 1. Log-likelihood
"""

# Define the optimized negative log-likelihood function for NBD regression
def NLL_nbd_reg_books2(params, X, y):
    # Extract parameters
    n, alpha, *betas = params  # n (dispersion), alpha (rate), and betas (coefficients)
    betas = np.array(betas)

    # Calculate exp(beta * X) for each record using matrix multiplication (vectorized)
    exp_betaX = np.exp(X @ betas)

    # Calculate log-likelihood components in a vectorized manner
    p1 = gammaln(n + y) - (gammaln(n) + gammaln(y + 1))  # gamma terms
    p2 = n * (np.log(alpha) - np.log(alpha + exp_betaX))
    p3 = y * (np.log(exp_betaX) - np.log(alpha + exp_betaX))

    # Sum the components to get the log-likelihood for each record
    ll = p1 + p2 + p3

    # Calculate the total negative log-likelihood
    nll = -np.sum(ll)

    return nll

"""##### 2. Optimize"""

# Set up the input data
X = np.array(df_books03.drop(['userid', 'barnesandnoble_purchases'], axis=1))  # Feature matrix
y = np.array(df_books03['barnesandnoble_purchases'])  # Target variable (number of purchases)

# Initial guess for parameters: n, alpha, and betas (1 dispersion + 1 alpha + number of features)
initial_params = np.ones(X.shape[1] + 2)

# Set bounds: no negative values for n and alpha
bounds = [(0.000001, None)] * 2 + [(None, None)] * X.shape[1]

# Perform MLE optimization
soln_nbd_reg_books2 = minimize(
    NLL_nbd_reg_books2,  # minimize the negative log-likelihood (equivalent to maximizing the log-likelihood)
    args=(X, y),  # input parameters (X and y)
    x0=initial_params,  # initial guess for parameters
    bounds=bounds,  # bounds for decision variables
    tol=1e-10,  # convergence tolerance
    options={'ftol': 1e-8}  # fractional tolerance
)

"""##### 3. Report estimated parameters and maximum value of the log-likelihood"""

# Extract optimized parameters
n_mle = soln_nbd_reg_books2.x[0]
alpha_mle = soln_nbd_reg_books2.x[1]
betas_mle = soln_nbd_reg_books2.x[2:]

# Print results
print(f'Estimated n (dispersion): {n_mle}')
print(f'Estimated alpha (rate): {alpha_mle}')
for i, beta in enumerate(betas_mle, start=1):
    print(f'Estimated beta_{i}: {beta}')
print(f'Maximum Log-Likelihood: {-soln_nbd_reg_books2.fun}')
mll_nbd_reg_books2 = -soln_nbd_reg_books2.fun

"""#### b) Predict the number of people with 0, ..., 20, 20+ purchases based on the NBD regression"""

def predict_nbd_reg_books2(params, X, y):
  # unpack parameters
  n, alpha, *betas = params # n, alpha, and the remaining parameters in betas

  # assume each group has m independent individuals, the expected number of people with k purchases is m * p(x = k)
  # assume each record is a separate group, then the expected number of people with k purchases is p(x = k)
  # calculate p(x = k) for each record and sum up to get the expected number of people with k purchases

  # calculate exp(beta*X) for each record using matrix multiplication
  exp_betaX = np.exp(X @ np.array(betas))

  # get unique values of y to calculate probabilities for each unique count
  unique_counts = np.unique(y)

  # calculate the probability p for the negative binomial distribution
  p = alpha / (alpha + exp_betaX)

  # create a PMF matrix for each unique count k across all samples
  pmf_matrix = np.array([
      nbinom.pmf(unique_counts, n, p_i) for p_i in p])

  # sum probabilities across all samples for each k value
  pred = np.sum(pmf_matrix, axis = 0) # sum along the samples (axis = 0) for each unique k

  # sort dictionary by visit count
  pred_dict = dict(zip(unique_counts, pred))
  pred_dict = dict(sorted(pred_dict.items()))

  return pred_dict

# make predictions
pred_nbd_reg_books2 = predict_nbd_reg_books2(soln_nbd_reg_books2.x, X, y)
pred_nbd_reg_books2

# create a dataframe to store actual counts
actual_df = df_books03.groupby('barnesandnoble_purchases')['userid'].count().reset_index()
actual_df.columns = ['NumberofPurchases', 'ActualCustomerCount']

# create a dataframe to store predicted counts
pred_df = pd.DataFrame({'NumberofPurchases': list(pred_nbd_reg_books2.keys()),
                        'PredictedCustomerCount': list(pred_nbd_reg_books2.values())})

# merge actual and predicted counts on NumberofPurchases
books2_nbd_reg = pd.merge(actual_df, pred_df, on = 'NumberofPurchases', how = 'outer').fillna(0)

# combine groups with number of purchases > 20
books2_nbd_reg_combined = books2_nbd_reg.copy()
books2_nbd_reg_combined.loc[books2_nbd_reg_combined['NumberofPurchases'] > 20, 'NumberofPurchases'] = 21
books2_nbd_reg_combined = books2_nbd_reg_combined.groupby('NumberofPurchases').sum().reset_index()

# convert number of purchases into integer
books2_nbd_reg_combined['NumberofPurchases'] = books2_nbd_reg_combined['NumberofPurchases'].astype(int)
books2_nbd_reg_combined

"""#### c) Explain how the predicted value are obtained using the case of 2 purchases"""

# Optimized parameters from the NBD regression
params = soln_nbd_reg_books2.x  # Optimized parameters from previous solution
target_count = 2  # Target purchase count

# Feature matrix X (your dataset without target variable)
# Assuming X is already defined in your environment

# Calculate exp(beta*X) for each record using matrix multiplication
exp_betaX = np.exp(X @ np.array(params[2:]))

# Calculate the probability parameter for the NBD
n = params[0]  # Dispersion
alpha = params[1]  # Rate
p = alpha / (alpha + exp_betaX)

# Calculate the PMF for the target count across all samples and sum the probabilities
predicted_probability_y_2 = np.sum([nbinom.pmf(target_count, n, p_i) for p_i in p])

predicted_probability_y_2

"""Step-by-Step Calculation of P(X = 2) in NBD Regression

1. **Calculate the Expected Count \(λi\)**

   For each observation \(i\), the expected count \(λi\) is given by:

   $$
   \mu_i = \exp(\beta_1 x_{1,i} + \beta_2 x_{2,i} + \beta_3 x_{3,i} + \beta_4 x_{4,i} + \beta_5 x_{5,i} + \beta_6 x_{6,i} + \beta_7 x_{7,i})
   $$

   where:
   - β1 ≈ -0.1033
   - β2 ≈ -0.0083
   - β3 ≈ 0.0284
   - β4 ≈ 0.0176
   - β5 ≈ 0.0573
   - β6 ≈ -0.2088
   - β7 ≈ -0.1026

2. **Compute the Probability of Exactly 2 Exposures**

   For each observation, we use the Negative Binomial probability mass function (PMF) to compute the probability that each individual has exactly 2 exposures, given by:

   $$
   P(X = 2) = \frac{\Gamma(n + 2)}{\Gamma(n) \times 2!} \times \big(\frac{\alpha}{\alpha + \mu_i}\big)^{n} \times \big(\frac{\mu_i}{\alpha + \mu_i}\big)^{2}
   $$
   
   where:
   - n = 0.0980
   - α = 0.1080

3. **Calculate P(X = 2) by Summation**

   We then sum up all the probabilities of exactly 2 exposures across all observations.
   $$
   P(X = 2) ≈ 320.030
   $$

#### d) Graph
"""

# Plotting the side-by-side bar chart for actual vs predicted counts using df_comparison
fig, ax = plt.subplots(figsize=(12, 6))
bar_width = 0.4  # Width of the bars

# Plot bars for actual and predicted counts
ax.bar(books2_nbd_reg_combined['NumberofPurchases'] - bar_width/2,
       books2_nbd_reg_combined['ActualCustomerCount'],
       bar_width,
       color='blue',
       edgecolor='black',
       label='Actual Number of People')

ax.bar(books2_nbd_reg_combined['NumberofPurchases'] + bar_width/2,
       books2_nbd_reg_combined['PredictedCustomerCount'],
       bar_width,
       color='orange',
       edgecolor='black',
       label='Predicted Number of People (NBD Regression Model)')

# Labeling the chart
ax.set_xlabel('Purchase Count')
ax.set_ylabel('Number of People')
ax.set_title("Actual vs. Predicted Number of People by Purchase Count using NBD Regression Model for `books02.csv`")
ax.legend()

# Customizing x-ticks to include "20+"
ax.set_xticks(books2_nbd_reg_combined['NumberofPurchases'])
ax.set_xticklabels([str(int(x)) if x < 21 else "20+" for x in books2_nbd_reg_combined['NumberofPurchases']])

# Show plot
plt.show()

"""### 10. Evaluate all the models developed using the log-likelihood ratio, AIC, and BIC.

What are your recommendations on which model to use based on each of these criteria? Are the recommendations consistent? Explain why you are
recommending the model you have selected. Are there any significant differences among the results from the
models? If so, what exactly are these differences? Discuss what you believe could be causing the differences.
"""

# create a summary dataframe to store relevant metrics
summary = pd.DataFrame({'Model': ['Poisson', 'NBD', 'Poisson Regression', 'NBD Regression'],
                        'Number of Parameters': [len(x) for x in [result3.x, nbd_result.x, soln_poisson_reg_books2.x,soln_nbd_reg_books2.x ]],
                        'Maximum Log-Likelihood': [max_log_likelihood, mll_nbd, mll_poisson_reg_books2, mll_nbd_reg_books2]
                        })

# define specific pairs to compare
pairs_to_compare = [
    ('Poisson', 'NBD'),
    ('Poisson', 'Poisson Regression'),
    ('Poisson Regression', 'NBD Regression'),
    ('NBD', 'NBD Regression')
]

# initialize an empty list to store log-likelihood ratios
results = []

# iterate through all possible pairs of models
for model1, model2 in pairs_to_compare:
  # get the log-likelihoods and number of parameters for the 2 models
  ll1 = summary.loc[summary['Model'] == model1, 'Maximum Log-Likelihood'].values[0]
  ll2 = summary.loc[summary['Model'] == model2, 'Maximum Log-Likelihood'].values[0]

  df1 = summary.loc[summary['Model'] == model1, 'Number of Parameters'].values[0]
  df2 = summary.loc[summary['Model'] == model2, 'Number of Parameters'].values[0]

  # log-likelihood ratio
  lr_stat = 2 * (ll2 - ll1)

  # calculate difference in df
  df_diff = abs(df2 - df1)

  # calculate p-value from chi-squared distribution
  p_value = 1 - chi2.cdf(lr_stat, df_diff)
  p_value = round(p_value, 5)

  # append the result
  results.append({
        'Simple Model': model1,
        'Complex Model': model2,
        'Log-Likelihood Ratio': lr_stat,
        'Degrees of Freedom Difference': df_diff,
        'Chi-Squared p-value': p_value})

# create a dataframe to store the pairwise results
comparison_df = pd.DataFrame(results)

comparison_df

# append the dataframe with AIC and BIC
summary['AIC'] = 2 * summary['Number of Parameters'] - 2 * summary['Maximum Log-Likelihood']
summary['BIC'] = np.log(np.sum(df_books01['number_of_people'])) * summary['Number of Parameters'] - 2 * summary['Maximum Log-Likelihood']

summary.round(2)

plt.figure(figsize=(12,6))
plt.plot(summary['AIC'], color = 'red', marker = 'o', label = 'AIC')
plt.plot(summary['BIC'], color = 'blue', marker = 'o', label = 'BIC')
plt.xticks(ticks = np.arange(len(summary['Model'])),labels = summary['Model'])
plt.xlabel('Model')
plt.ylabel('AIC / BIC')
plt.legend()
plt.grid(axis = 'y')
plt.title('AIC and BIC for All Models')
plt.show()

import matplotlib.pyplot as plt

# Observed values
observed_values = books2_nbd_reg_combined['ActualCustomerCount'].values

# Predictions from different models
poisson_predictions = df_comparison['Predicted Number of People'].values
nbd_predictions = df_comparison2['Predicted Number of People'].values
poisson_regression_predictions = books2_poisson_reg_combined['PredictedCustomerCount'].values
nbd_regression_predictions = books2_nbd_reg_combined['PredictedCustomerCount'].values

# Set up the x-axis for 10 data points
x = np.arange(len(observed_values))

# Plot observed values as a bar chart
plt.figure(figsize=(14,8))
plt.bar(x, observed_values, color='skyblue', label='Actual', alpha=0.7)

# Plot predictions from each model as line graphs
plt.plot(x, poisson_predictions, color='orange', marker='o', linestyle='-', label='Poisson')
plt.plot(x, nbd_predictions, color='green', marker='o', linestyle='-', label='NBD')
plt.plot(x, poisson_regression_predictions, color='purple', marker='o', linestyle='-', label='Poisson Regression')
plt.plot(x, nbd_regression_predictions, color='blue', marker='o', linestyle='-', label='NBD Regression')

# Add labels and title
plt.xlabel('Data Point')
plt.ylabel('Count')
plt.title('Observed Values vs Model Predictions for Barnes & Noble Sales')
plt.legend()

# Show the plot
plt.show()